export const FALLBACK_PLACES = [
  {
    id: "fallback_burj_khalifa",
    name: "Burj Khalifa",
    lat: 25.197197,
    lng: 55.274376,
    category: "attraction",
    city: "Dubai",
    address: "1 Sheikh Mohammed bin Rashid Blvd, Downtown Dubai",
    rating: 4.9,
    website: "https://www.burjkhalifa.ae/",
    actionLabel: "Book Viewing Deck Tickets",
    actionUrl: "https://www.burjkhalifa.ae/en/index.aspx",
    actionType: "tickets",
    sourceType: "official",
    sourceName: "Burj Khalifa Official Booking Portal",
    verifiedAt: "2026-09-09",
    actionStatus: "verified"
  },
  {
    id: "fallback_dubai_frame",
    name: "Dubai Frame",
    lat: 25.235651,
    lng: 55.300588,
    category: "attraction",
    city: "Dubai",
    address: "Zabeel Park Jogging Track, Za'abeel",
    rating: 4.7,
    website: "https://www.dubaiframe.ae/",
    actionLabel: "Book Dubai Frame Tickets",
    actionUrl: "https://www.dubaiframe.ae/en",
    actionType: "tickets",
    sourceType: "official",
    sourceName: "Dubai Frame Official Portal",
    verifiedAt: "2026-09-09",
    actionStatus: "verified"
  },
  {
    id: "fallback_museum_future",
    name: "Museum of the Future",
    lat: 25.219154,
    lng: 55.281987,
    category: "culture",
    city: "Dubai",
    address: "Sheikh Zayed Rd, Trade Centre",
    rating: 4.8,
    website: "https://museumofthefuture.ae/",
    actionLabel: "Book Visitor Passes",
    actionUrl: "https://museumofthefuture.ae/en/plan-your-visit",
    actionType: "tickets",
    sourceType: "official",
    sourceName: "Museum of the Future Official",
    verifiedAt: "2026-09-09",
    actionStatus: "verified"
  },
  {
    id: "fallback_dubai_mall",
    name: "The Dubai Mall",
    lat: 25.197282,
    lng: 55.279663,
    category: "shopping",
    city: "Dubai",
    address: "Financial Center Street, Along Sheikh Zayed Road",
    rating: 4.7,
    website: "https://thedubaimall.com/",
    actionLabel: "Visit Mall Directory",
    actionUrl: "https://thedubaimall.com/en/plan-your-visit",
    actionType: "website",
    sourceType: "official",
    sourceName: "The Dubai Mall Official",
    verifiedAt: "2026-09-09",
    actionStatus: "verified"
  },
  {
    id: "fallback_kite_beach",
    name: "Kite Beach Sunset & Cafes",
    lat: 25.1654,
    lng: 55.2086,
    category: "outdoor",
    city: "Dubai",
    address: "Kite Beach, Umm Suqeim 1",
    rating: 4.8,
    website: "https://www.kitebeach.ae/",
    actionLabel: "Explore Beach Guide",
    actionUrl: "https://www.kitebeach.ae/",
    actionType: "website",
    sourceType: "official",
    sourceName: "Kite Beach Official",
    verifiedAt: "2026-09-09",
    actionStatus: "verified"
  },
  {
    id: "fallback_yas_island",
    name: "Yas Island Theme Parks",
    lat: 24.4950,
    lng: 54.6097,
    category: "entertainment",
    city: "Abu Dhabi",
    address: "Yas Island, Abu Dhabi",
    rating: 4.8,
    website: "https://www.yasisland.ae/",
    actionLabel: "Book Theme Park Passes",
    actionUrl: "https://www.yasisland.com/en/tickets",
    actionType: "tickets",
    sourceType: "official",
    sourceName: "Yas Island Official Portal",
    verifiedAt: "2026-09-09",
    actionStatus: "verified"
  },
  {
    id: "fallback_louvre_ad",
    name: "Louvre Abu Dhabi",
    lat: 24.5337,
    lng: 54.3986,
    category: "culture",
    city: "Abu Dhabi",
    address: "Saadiyat Cultural District, Saadiyat Island",
    rating: 4.9,
    website: "https://www.louvreabudhabi.ae/",
    actionLabel: "Buy Admission Tickets",
    actionUrl: "https://www.louvreabudhabi.ae/en/buy-ticket",
    actionType: "tickets",
    sourceType: "official",
    sourceName: "Louvre Abu Dhabi Official",
    verifiedAt: "2026-09-09",
    actionStatus: "verified"
  },
  {
    id: "fallback_szgm",
    name: "Sheikh Zayed Grand Mosque",
    lat: 24.4128,
    lng: 54.4750,
    category: "attraction",
    city: "Abu Dhabi",
    address: "Sheikh Rashid Bin Saeed Street",
    rating: 4.9,
    website: "https://www.szgmc.gov.ae/",
    actionLabel: "Register Free Visitor Pass",
    actionUrl: "https://www.szgmc.gov.ae/en/Booking-Visitor-Pass",
    actionType: "registration",
    sourceType: "official",
    sourceName: "SZGMC Official Visitor Portal",
    verifiedAt: "2026-09-09",
    actionStatus: "verified"
  },
  {
    id: "fallback_tom_serge",
    name: "Tom & Serg Specialty Coffee",
    lat: 25.1413,
    lng: 55.2195,
    category: "cafe",
    city: "Dubai",
    address: "15A Street, Al Quoz",
    rating: 4.5,
    website: "https://tomandserg.com/",
    actionLabel: "Reserve Table / View Menu",
    actionUrl: "https://tomandserg.com/",
    actionType: "reservation",
    sourceType: "official",
    sourceName: "Tom & Serg Official",
    verifiedAt: "2026-09-09",
    actionStatus: "verified"
  },
  {
    id: "fallback_pierchic",
    name: "Pierchic Fine Dining",
    lat: 25.1325,
    lng: 55.1843,
    category: "food",
    city: "Dubai",
    address: "Jumeirah Al Qasr, Madinat Jumeirah",
    rating: 4.7,
    website: "https://www.jumeirah.com/",
    actionLabel: "Reserve Dining Table",
    actionUrl: "https://www.jumeirah.com/en/dine/dubai/al-qasr-pierchic",
    actionType: "reservation",
    sourceType: "official",
    sourceName: "Jumeirah Pierchic Official",
    verifiedAt: "2026-09-09",
    actionStatus: "verified"
  },
  {
    id: "fallback_atlantis",
    name: "Atlantis Aquaventure Waterpark",
    lat: 25.1304,
    lng: 55.1171,
    category: "entertainment",
    city: "Dubai",
    address: "Crescent Rd, The Palm Jumeirah",
    rating: 4.7,
    website: "https://www.atlantis.com/",
    actionLabel: "Book Waterpark Passes",
    actionUrl: "https://www.atlantis.com/dubai/aquaventure-waterpark",
    actionType: "tickets",
    sourceType: "official",
    sourceName: "Atlantis Aquaventure Official",
    verifiedAt: "2026-09-09",
    actionStatus: "verified"
  },
  {
    id: "fallback_global_village",
    name: "Global Village Dubai",
    lat: 25.0683,
    lng: 55.3045,
    category: "entertainment",
    city: "Dubai",
    address: "Sheikh Mohammed Bin Zayed Road",
    rating: 4.6,
    website: "https://www.globalvillage.ae/",
    actionLabel: "Buy Entry Tickets",
    actionUrl: "https://www.globalvillage.ae/en/buy-tickets",
    actionType: "tickets",
    sourceType: "official",
    sourceName: "Global Village Official",
    verifiedAt: "2026-09-09",
    actionStatus: "verified"
  },
  {
    id: "fallback_jebel_jais",
    name: "Jebel Jais Drive & Peak Zipline",
    lat: 25.9526,
    lng: 56.1264,
    category: "outdoor",
    city: "Ras Al Khaimah",
    address: "Jebel Jais Mountain Road",
    rating: 4.9,
    website: "https://visitjebeljais.com/",
    actionLabel: "Book Jais Zipline Adventure",
    actionUrl: "https://visitjebeljais.com/adventures/jais-flight/",
    actionType: "booking",
    sourceType: "official",
    sourceName: "Visit Jebel Jais Official",
    verifiedAt: "2026-09-09",
    actionStatus: "verified"
  },
  {
    id: "fallback_al_serkal",
    name: "Alserkal Avenue Art & Coffee",
    lat: 25.1419,
    lng: 55.2268,
    category: "culture",
    city: "Dubai",
    address: "17th St, Al Quoz 1",
    rating: 4.8,
    website: "https://alserkal.online/",
    actionLabel: "Explore Art Exhibitions",
    actionUrl: "https://alserkal.online/",
    actionType: "website",
    sourceType: "official",
    sourceName: "Alserkal Avenue Official",
    verifiedAt: "2026-09-09",
    actionStatus: "verified"
  }
];
